version: '2.2'

services:
  cryptoapp:
    image: crypto
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      cryptodb:
        condition: service_healthy
    ports:
      - 8087:8080
  cryptodb:
    volumes:
     - ./db:/docker-entrypoint-initdb.d
    image: mysql
    ports:
    - "2012:3306"
    restart: always
    command: --lower_case_table_names=1
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=cryptotrader
      - MYSQL_USER=rollnrock
      - MYSQL_PASSWORD=iddqd
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10